#pragma once

// DEBUG
#define DEBUG_LEVEL DBG_NONE
#define DEBUG_PORT 115200

// HOMEKIT
#define HOMEKIT_PASSWORD "111-11-111"
#define HOMEKIT_REPORT_PERIOD_MS 5000

// WEATHER STATION
#define DHT_PIN D1
#define DHT_TYPE DHT22

// CONTACT SENSOR
#define CONTACT_SENSOR_PIN D5

// ACTUATOR
#define ACTUATOR_PIN D2
#define ACTUATOR_TIMEOUT_MS 30000
