#pragma once

// DEBUG
#define DEBUG_LEVEL DBG_NONE
#define DEBUG_PORT 115200

// HOMEKIT
#define HOMEKIT_PASSWORD "111-11-111"

// WEATHER STATION
#define DHT_PIN D1
#define DHT_TYPE DHT22

// CONTROLLER
#define CONTACT_SENSOR_PIN D5
#define ACTUATOR_PIN D2
#define ACTUATOR_TIMEOUT_MS 60000
